# $bg = /home/autumn/sync/images/bg/hypr.png
# $bg = /home/autumn/sync/images/bg/sg_taliyah.jpg
# $bg = /home/autumn/sync/images/bg/madoka_3.webp
# $bg = $HOME/sync/images/bg/hesche-mountains.jpg
$bg = $HOME/sync/images/bg/feeling_cute.png

wallpaper {
	monitor = DP-3
	path = $bg
}
