#========#
# LAUNCH #
#========#

$terminal = ghostty

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/appearance.conf


#======#
# INIT #
#======#

exec-once = hyprpaper
exec-once = waybar
exec-once = hypridle


#========#
# LAYOUT #
#========#

general {
	#gaps_in = 4
	#gaps_out = 8 
	gaps_in = 0
	gaps_out = 0

	border_size = 1

	col.active_border = rgb(3e8fb0)
	#col.inactive_border = rgba(59595988)
	col.inactive_border = rgba(232136e6)

	# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
	allow_tearing = false

	layout = dwindle
}

decoration {
	dim_inactive = true
	dim_strength = 0.2
}

dwindle {
	pseudotile = true
	preserve_split = true
	force_split = 2
}

master {
	new_status = master
	new_on_active = after
}


#=======#
# INPUT #
#=======#

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
	repeat_delay = 300
	repeat_rate = 50

	kb_layout = us
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = 1
	sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
	touchpad {
		natural_scroll = false
	}
}


#========================#
# WINDOWS AND WORKSPACES #
#========================#

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = match:class .* suppress_event

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#windowrule = match:class ^$ title:^$xwayland nofocus floating:1 fullscreen:0 pinned:0


#============#
# BACKGROUND #
#============#

#   https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, 1920x1080@143.992Hz, 0x0, 1
monitor = DP-3, 1920x1080@143.992Hz, 0x0, 1

misc {
	disable_hyprland_logo = true # allow default logo and anime wallpapers
	force_default_wallpaper = 2 # set default wallpaper to the anime girl
}
