# environment
keyd hyprland hyprpaper hypridle
waybar gsimplecal swaync rofi
pavucontrol pipewire pipewire-pulse wireplumber
iw wireless-regdb
wl-clipboard grim slurp


# terminal apps
ghostty foot neovim yazi mpv
zsh zsh-autosuggestions zsh-syntax-highlighting starship


# cli tools
fastfetch unzip wget less openssh 
fzf ripgrep fd eza zoxide bc
#   info
man-db man-pages wikiman tealdeer 


# programming
bash-language-server clang lua-language-server


# fonts
ttf-jetbrains-mono-nerd


# gui apps
firefox
discord steam
code
krita
reaper surge-xt


# programming
base-devel git gcc clang
cmake make ninja
# vulkan-devel
vulkan-headers vulkan-validation-layers spirv-headers vulkan-utility-libraries
vulkan-tools # volk vulkan-extra-layers vulkan-extra-tools
glfw-wayland
shaderc glslang spirv-tools

