# environment
keyd hyprland hyprpaper hypridle waybar rofi swaync
pavucontrol pipewire pipewire-pulse wireplumber
iw wireless-regdb
wl-clipboard grim slurp


# terminal apps
ghostty    neovim yazi
zsh zsh-autosuggestions zsh-syntax-highlighting starship


# cli tools
base-devel git gcc openssh
man-db man-pages wikiman tealdeer 
fastfetch unzip wget less
fzf ripgrep fd eza zoxide

# programming
bash-language-server clang lua-language-server


# fonts
ttf-monofur ttf-jetbrains-mono-nerd


# gui apps
firefox discord steam
code
krita
reaper surge-xt
