# Oneshot : tap instead of holding.

[ids]
*


[main]
include main


[shift]
include shift


# ==== ==== ==== #
#      CTRL      #
# ==== ==== ==== #

[ctrl_left:C]
# Row 1
	o = enter
	] = tab
# Row 2
	s = layer(shift)
	h = left
	k = up
	j = down
	l = right
	' = C-delete
# Row 3
	c = oneshot(control)
	, = C-pageup
	. = C-pagedown

[ctrl_right:C]
	capslock = C-backspace
	tab = S-tab


# ==== ==== ==== #
#      TOKN      #
# ==== ==== ==== #

[token_left]
include token
	capslock = clear()
	' = delete
	] = tab

	tab = clear()


[token_right]
include token
	' = clear()
	capslock = backspace
	tab = capslock
